
name: mi primer pipeline

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir mensajes
        run: echo "Hola, esto es un Pipeline en  Actions!"
